name: Build

on: [push, pull_request]
    
jobs:
  build:
    runs-on: windows-latest

    steps:
    
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
    
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install MSBuild
        uses: microsoft/setup-msbuild@v1
      
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn
      
      - name: Build
        run: yarn build
